src/binding.rs
src/bootstrap.rs
src/main.rs
src/repl.rs
src/script.rs

This makes the code in the standard style.

Run cargo fmt

---

.github/workflows/ci.yml

tools: add basic CI action

---

core/src/module.rs
core/src/script.rs

s/exception/stack_trace
Fixes: https://github.com/jstime/jstime/issues/34

core: fix stack traces

---

Cargo.lock
cli/Cargo.toml
cli/build.rs
cli/main.rs
core/Cargo.toml
core/src/builtins/mod.rs
core/src/isolate_state.rs
core/src/lib.rs

Add snapshots

---

GOVERNANCE.md
README.md

This is a first pass at general governance for the project.
Highlight include:
* collaborators
- can land prs
- can elect chair
* pr review process
- must have 1 review
- no objections
- objection can be overridden by rough consensus
* rough consensus
- determined by chair
* collaborator nomination process
Closes: https://github.com/jstime/jstime/issues/22

doc: introduce basic governance

---

GOVERNANCE.md

* Clarify super majority.
* Add missing "inspired".
* Add periods at the ends of sentences.

doc: minor fixes to GOVERNANCE.md

---

README.md

doc: pronouns for bengl

---

GOVERNANCE.md

Realized that there was no process for changing governance, PTAL

doc: document changing the governance

---

README.md

meta: add jalafel to collaborators

---

cli/main.rs
core/src/builtins/mod.rs
core/src/lib.rs

/cc @devsnek @bengl I'm not sure that this actually makes things better PTAL

chore: fix clippy warning for beta rust toolchain

---

.github/workflows/release.yml

testing something fancy and new 😇

tools: update release script

---

.github/workflows/release.yml

tools: tiny tweak on release note generation

---

.github/workflows/release.yml

tools: update release workflow

---

.github/workflows/release.yml

Create a more in depth pipeline that will hopefully work this time.
- create release as draft with notes prior to assets being uploaded
- upload assets
- publish release once assets are uploaded

tools: actually fix release scipt

---

.github/workflows/release.yml

Simplify process and create GitHub release first as non-draft
and then push the assets.

tools: ok this is finally it

---

.github/workflows/release.yml

API is now a POST and different end point

tools: release notes API is a POST now

---

.github/workflows/release.yml

Improvements to the GitHub API means we can do even less!

tools: simplify release script

---

.github/workflows/release.yml

tools: update workflow to use gh cli

---

Cargo.lock

updating various dependencies via `cargo update`

deps: various dep updates

---

cli/Cargo.toml
core/Cargo.toml

chore: update to 2021 edition of rust

---

Cargo.lock
Cargo.toml
cli/build.rs
cli/main.rs
core/Cargo.toml
core/src/isolate_state.rs
core/src/lib.rs

remove snapshots because the API has been removed

snapshots: temporarily remove snapshots to update v8

---

.devcontainer.json

This pull request introduces a new development environment configuration for Rust. The `.devcontainer.json` file has been added, which sets up a Rust development environment using the latest Rust image from Microsoft's container registry. This change will allow developers to have a consistent development environment for this project.

tools: add devcontainer
